# Generated by Django 5.2.1 on 2025-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True, verbose_name='URL'),
        ),
    ]
